DELETE FROM FINALPROJECT.STATUSES;
INSERT INTO FINALPROJECT.STATUSES (ID, NAME) VALUES (0, 'OPENED');
INSERT INTO FINALPROJECT.STATUSES (ID, NAME) VALUES (1, 'CONFIRMED');
INSERT INTO FINALPROJECT.STATUSES (ID, NAME) VALUES (3, 'PAID');
INSERT INTO FINALPROJECT.STATUSES (ID, NAME) VALUES (4, 'CLOSED');

DELETE FROM FINALPROJECT.ROLES;
INSERT INTO FINALPROJECT.ROLES (ID, NAME) VALUES (0, 'ADMIN');
INSERT INTO FINALPROJECT.ROLES (ID, NAME) VALUES (1, 'MANAGER');
INSERT INTO FINALPROJECT.ROLES (ID, NAME) VALUES (2, 'CLIENT');

DELETE FROM FINALPROJECT.USERS;
DELETE FROM FINALPROJECT.USERS_INFO;

INSERT INTO FINALPROJECT.USERS (ID, LOGIN, PASSWORD, ROLE_ID, LOCALE) VALUES (1, 'admin', '8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918', 0, 'en');
INSERT INTO FINALPROJECT.USERS_INFO (ID, NAME, SURNAME, GENDER, EMAIL, CITY) VALUES (1, 'Yehor', 'Y', '0', 'admin@email.com', 'Kharkiv');

DELETE FROM FINALPROJECT.TOURS;
INSERT INTO FINALPROJECT.TOURS (TYPE, HOTEL, PRICE, HUMAN_AMOUNT, ISFIRE, STATUS, DISCOUNT, USER_ID) VALUES ('Test', 'Hotel test', 11500, 2, 1, 0, 10, null);
